name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Inventory Service image
      uses: docker/build-push-action@v5
      with:
        context: ./inventory-service
        file: ./inventory-service/Dockerfile
        push: false
        tags: micro-service/inventory-service:latest
    
    - name: Build Order Service image
      uses: docker/build-push-action@v5
      with:
        context: ./order-service
        file: ./order-service/Dockerfile
        push: false
        tags: micro-service/order-service:latest
