name: Build and Test Microservices

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['inventory-service', 'order-service']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: '${{ matrix.service }}/go.sum'

    - name: Build ${{ matrix.service }}
      run: go build -v .
      working-directory: ${{ matrix.service }}

    - name: Run tests for ${{ matrix.service }}
      run: go test -v ./...
      working-directory: ${{ matrix.service }}

    - name: Run go vet for ${{ matrix.service }}
      run: go vet ./...
      working-directory: ${{ matrix.service }}
